import{a as m,S as g,i as a}from"./assets/vendor-67BWzQEt.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const y="51062655-c6be70d0f875c8df0d60bf3cc",h="https://pixabay.com/api/";function c(t){return m.get(h,{params:{key:y,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data)}const b=document.querySelector(".gallery");document.querySelector(".loader");const L=new g(".gallery a");function S(t){const o=document.querySelector(".gallery"),s=t.map(({webformatURL:i,largeImageURL:e,tags:r,likes:n,views:u,comments:d,downloads:p})=>`<li>
        <a href="${e}">
          <img src="${i}" alt="${r}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> <span>${n}</span></p>
          <p><b>Views:</b> <span>${u}</span></p>
          <p><b>Comments:</b> <span>${d}</span></p>
          <p><b>Downloads:</b> <span>${p}</span></p>
        </div>
      </li>`).join("");o.insertAdjacentHTML("beforeend",s),L.refresh()}function v(){b.innerHTML=""}function E(){const t=document.querySelector(".loader");t&&t.classList.add("visible")}function l(){const t=document.querySelector(".loader");t&&t.classList.remove("visible")}const f=document.querySelector(".form"),q=f.elements["search-text"];f.addEventListener("submit",async t=>{t.preventDefault();const o=q.value.trim();if(!o){a.error({message:"Please enter a search term"});return}v(),E(),c(o).then(s=>{l()}).catch(s=>{l(),a.error({message:"Error response"})});try{const s=await c(o);s.hits.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",iconUrl:"/goit-js-hw-10/img/bi_x-octagon.svg",progressBarColor:"#b51b1b",color:"#ef4040",transitionIn:"fadeInDown",maxWidth:"432px"}):S(s.hits)}catch(s){a.error({message:"Something went wrong, try again later"}),console.error(s)}finally{l()}});
//# sourceMappingURL=index.js.map
