import{a as m,S as p,i as a}from"./assets/vendor-67BWzQEt.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const u="51062655-c6be70d0f875c8df0d60bf3cc",d="https://pixabay.com/api/";function h(o){return m.get(d,{params:{key:u,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data)}const y=document.querySelector(".gallery");document.querySelector(".loader");const b=new p(".gallery a");function L(o){const r=document.querySelector(".gallery"),i=o.map(({webformatURL:n,largeImageURL:e,tags:t,likes:s,views:c,comments:f,downloads:g})=>`<li>
        <a href="${e}">
          <img src="${n}" alt="${t}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> <span>${s}</span></p>
          <p><b>Views:</b> <span>${c}</span></p>
          <p><b>Comments:</b> <span>${f}</span></p>
          <p><b>Downloads:</b> <span>${g}</span></p>
        </div>
      </li>`).join("");r.insertAdjacentHTML("beforeend",i),b.refresh()}function S(){y.innerHTML=""}function x(){const o=document.querySelector(".loader");o&&o.classList.add("visible")}function v(){const o=document.querySelector(".loader");o&&o.classList.remove("visible")}const l=document.querySelector(".form"),w=l.elements["search-text"];l.addEventListener("submit",o=>{o.preventDefault();const r=w.value.trim();if(!r){a.error({message:"Please enter a search term",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",iconUrl:"/goit-js-hw-10/img/bi_x-octagon.svg",progressBarColor:"#b51b1b",color:"#ef4040",transitionIn:"fadeInDown",maxWidth:432});return}S(),x(),h(r).then(i=>{if(i.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",iconUrl:"/goit-js-hw-10/img/bi_x-octagon.svg",progressBarColor:"#b51b1b",color:"#ef4040",transitionIn:"fadeInDown",maxWidth:432});return}L(i.hits)}).catch(i=>{a.error({message:"Something went wrong, try again later",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",iconUrl:"/goit-js-hw-10/img/bi_x-octagon.svg",progressBarColor:"#b51b1b",color:"#ef4040",transitionIn:"fadeInDown",maxWidth:432}),console.error(i)}).finally(()=>{v()})});
//# sourceMappingURL=index.js.map
